// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmOADY7gWQk7C0aBMU5kkkAWeMA221vRY',
    appId: '1:317572974295:web:517acc33131773491f5292',
    messagingSenderId: '317572974295',
    projectId: 'prac1-4def4',
    authDomain: 'prac1-4def4.firebaseapp.com',
    storageBucket: 'prac1-4def4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiDzdx6qqTwa6k8dW-jtix_cB4zE6HnlU',
    appId: '1:317572974295:android:33e7c5e3bb209dcc1f5292',
    messagingSenderId: '317572974295',
    projectId: 'prac1-4def4',
    storageBucket: 'prac1-4def4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoaTInL4GMuabrOuTvFwhJDF4mwH1eJeI',
    appId: '1:317572974295:ios:506eae6b7de2fe461f5292',
    messagingSenderId: '317572974295',
    projectId: 'prac1-4def4',
    storageBucket: 'prac1-4def4.appspot.com',
    iosClientId: '317572974295-odtfh51lbo30gu4att7bcnje5bava1cp.apps.googleusercontent.com',
    iosBundleId: 'com.topzee.prac1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoaTInL4GMuabrOuTvFwhJDF4mwH1eJeI',
    appId: '1:317572974295:ios:506eae6b7de2fe461f5292',
    messagingSenderId: '317572974295',
    projectId: 'prac1-4def4',
    storageBucket: 'prac1-4def4.appspot.com',
    iosClientId: '317572974295-odtfh51lbo30gu4att7bcnje5bava1cp.apps.googleusercontent.com',
    iosBundleId: 'com.topzee.prac1',
  );
}
